In [1]:
# Importing required libraries for data handling
import pandas as pd
import numpy as np

In [5]:
# Loading dataset and assigning column names
# Also treating '?' as missing values during loading

columns = [
    "symboling", "normalized_losses", "make", "fuel_type",
    "aspiration", "num_of_doors", "body_style", "drive_wheels",
    "engine_location", "wheel_base", "length", "width", "height",
    "curb_weight", "engine_type", "num_of_cylinders", "engine_size",
    "fuel_system", "bore", "stroke", "compression_ratio",
    "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"
]

df = pd.read_csv("../data/raw/automobile.csv", names=columns, na_values="?")

df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [6]:
# Function to get overall understanding of dataset

def data_overview(df):
    print("Shape of dataset:", df.shape)
    
    print("\nDataset Info:")
    df.info()
    
    print("\nStatistical Summary:")
    print(df.describe())

# Call function
data_overview(df)

Shape of dataset: (205, 26)

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized_losses  164 non-null    float64
 2   make               205 non-null    object
 3   fuel_type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num_of_doors       203 non-null    object
 6   body_style         205 non-null    object
 7   drive_wheels       205 non-null    object
 8   engine_location    205 non-null    object
 9   wheel_base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb_weight        205 non-null    int64
 14  engine_type        205 non-null    object
 15  num_of_cylinders   205 non-null    object
 16  engine_size        205 non-null    int64
 17  fuel_system        205 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression_ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak_rpm           203 non-null    float64
 23  city_mpg           205 non-null    int64
 24  highway_mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

Statistical Summary:
        symboling  normalized_losses  wheel_base      length       width  \
count  205.000000         164.000000  205.000000  205.000000  205.000000
mean     0.834146         122.000000   98.756585  174.049268   65.907805
std      1.245307          35.442168    6.021776   12.337289    2.145204
min     -2.000000          65.000000   86.600000  141.100000   60.300000
25%      0.000000          94.000000   94.500000  166.300000   64.100000
50%      1.000000         115.000000   97.000000  173.200000   65.500000
75%      2.000000         150.000000  102.400000  183.100000   66.900000
max      3.000000         256.000000  120.900000  208.100000   72.300000

           height  curb_weight  engine_size        bore      stroke  \
count  205.000000   205.000000   205.000000  201.000000  201.000000
mean    53.724878  2555.565854   126.907317    3.329751    3.255423
std      2.443522   520.680204    41.642693    0.273539    0.316717
min     47.800000  1488.000000    61.000000    2.540000    2.070000
25%     52.000000  2145.000000    97.000000    3.150000    3.110000
50%     54.100000  2414.000000   120.000000    3.310000    3.290000
75%     55.500000  2935.000000   141.000000    3.590000    3.410000
max     59.800000  4066.000000   326.000000    3.940000    4.170000

       compression_ratio  horsepower     peak_rpm    city_mpg  highway_mpg  \
count         205.000000  203.000000   203.000000  205.000000   205.000000
mean           10.142537  104.256158  5125.369458   25.219512    30.751220
std             3.972040   39.714369   479.334560    6.542142     6.886443
min             7.000000   48.000000  4150.000000   13.000000    16.000000
25%             8.600000   70.000000  4800.000000   19.000000    25.000000
50%             9.000000   95.000000  5200.000000   24.000000    30.000000
75%             9.400000  116.000000  5500.000000   30.000000    34.000000
max            23.000000  288.000000  6600.000000   49.000000    54.000000

              price
count    201.000000
mean   13207.129353
std     7947.066342
min     5118.000000
25%     7775.000000
50%    10295.000000
75%    16500.000000
max    45400.000000

In [7]:
# Checking number of missing values in each column

df.isnull().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_of_doors          2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_of_cylinders      0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

In [8]:
# Filling missing values:
# * Numerical columns → median
# * Categorical columns → mode

for col in df.columns:
    
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0])
    
    else:
        df[col].fillna(df[col].median())

# Verify missing values handled
df.isnull().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_of_doors          2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_of_cylinders      0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

In [9]:
# Converting necessary columns to numeric type

num_cols = [
    "normalized_losses", "wheel_base", "length", "width", "height",
    "curb_weight", "bore", "stroke", "compression_ratio",
    "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [16]:
# Handle missing values again after type conversion

for col in df.columns:
    
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0])
    
    else:
        df[col].fillna(df[col].median())

# Check again
df.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_of_doors         0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_of_cylinders     0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

In [10]:
# Remove duplicate rows if present

df.drop_duplicates(inplace=True)

In [17]:
# Standardizing categorical values:
# convert to lowercase and remove extra spaces

for col in df.columns:
    
    if df[col].dtype == "object":
        df[col] = df[col].str.lower().str.strip()

In [18]:
# Final check of dataset after cleaning

print("Final Shape:", df.shape)
print("\nFinal Missing Values:\n", df.isnull().sum())
print("\nFinal Data Types:\n", df.dtypes)

Final Shape: (205, 26)

Final Missing Values:
 symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_of_doors         0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_of_cylinders     0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

Final Data Types:
 symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_of_doors          object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_of_cylinders      object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [19]:
df.describe(include='all')

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,205.000000,205.000000,205,205,205,205,205,205,205,205.000000,...,205.000000,205,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
unique,NaN,NaN,22,2,2,2,5,3,2,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,toyota,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,185,168,116,96,120,202,NaN,...,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.834146,120.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,...,126.907317,NaN,3.329366,3.256098,10.142537,104.165854,5126.097561,25.219512,30.751220,13150.307317
std,1.245307,31.805105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,...,41.642693,NaN,0.270858,0.313634,3.972040,39.529733,477.035772,6.542142,6.886443,7879.121326
min,-2.000000,65.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,101.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,97.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,1.000000,115.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,137.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [20]:
# Saving cleaned dataset to processed folder

df.to_csv("../data/processed/cleaned_data.csv", index=False)

In [21]:
# Data Cleaning 
# - Missing values were handled in all columns
# - Numeric columns were converted to proper data types
# - Duplicate rows were removed
# - Categorical values were standardized (lowercase, no extra spaces)
# - Cleaned dataset saved for further analysis